###theme: jekyll-theme-architect
theme: jekyll-theme-leap-day
title: BSMP Adv Coders ðŸ¤–
description: BSMP Adv Coders ðŸ¤– GitHub Pages.
#permalink: pretty
# Menu items
menu:  
  - title: "Home"  
    url: "/"  
  - title: "Getting Started"  
    url: "/other/Getting-Started"  
  - title: "Documentation"  
    url: "/docs/README"  